# Generated by Django 3.1.2 on 2020-10-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
    ]
