# Generated by Django 3.1.2 on 2020-10-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactinscription',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
